name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run simple validation test
      - name: Run simple validation test
        run: |
          echo "Running simple validation..."
          if [ ! -f "Backend/pom.xml" ]; then
            echo "Backend/pom.xml not found!"
            exit 1
          fi
          if [ ! -f "Frontend/package.json" ]; then
            echo "Frontend/package.json not found!"
            exit 1
          fi
          echo "Validation successful!"

      # Step 3: Set up Java for running tests
      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin' # Specify the Java distribution

      # # Step 4: Run backend tests
      # - name: Run backend tests
      #   working-directory: Backend
      #   run: mvn test

      # Step 5: Deploy to VM (only if tests pass)
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            # Exit immediately if a command exits with a non-zero status.
            # set -e

            # Navigate to the project directory
            cd wanderwise

            # Pull the latest changes from the main branch
            git pull origin main

            # Write the environment variables from GitHub Secrets to the .env file
            echo "${{ secrets.ENV_FILE }}" > .env

            # Stop and remove old containers and networks
            docker-compose down --remove-orphans

            # Rebuild the Docker images without cache to ensure all changes are included
            docker-compose build --no-cache

            # Create and start the new containers in detached mode
            docker-compose up -d

            # Clean up unused Docker images to save space
            docker image prune -f